# Generated by Django 4.2.1 on 2023-05-17 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateVacationDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('imageURL', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('role', models.CharField(default='user', max_length=100)),
                ('activation_code', models.CharField(max_length=36)),
                ('activation_expiry_date', models.DateTimeField()),
                ('active', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='PublicVacationDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('imageURL', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
